var app = getApp();

var pageData = {
  data: { 
    "title_ele1": { "type": "title-ele", "style": "opacity:1;line-height:58.59375rpx;background-color:#efefef;border-color:rgb(34, 34, 34);border-style:none;color:#666;font-size:32.8125rpx;margin-left:auto;margin-right:auto;", "content": "以下内容仅作为匹配用途，绝对保密，请真实填写。", "customFeature": { "mode": 1, "markColor": "rgb(120, 63, 4)", "boxColor": "#000", "boxR": "5px", "boxStyle": false, "boxX": "0", "boxY": "0", "action": "inner-link", "inner-page-link": "prePage" }, "animations": [], "page_form": "", "compId": "title_ele1", "parentCompid": "title_ele1", "markColor": "rgb(120, 63, 4)", "mode": 1, "itemType": "title-ele", "itemParentType": null, "itemIndex": "title_ele1", "eventParams": "{\"inner_page_link\":\"\\\/pages\\\/prePage\\\/prePage\",\"is_redirect\":0}", "eventHandler": "tapInnerLinkHandler" },
  
   "form_vessel2": { "type": "form-vessel", "style": "background-color:rgba(0, 0, 0, 0);opacity:1;margin-left:auto;", "content": [{ "type": "select-ele", "style": "background-color:rgba(0, 0, 0, 0);margin-top:0;line-height:65.625rpx;opacity:1;margin-left:auto;margin-right:auto;width:750rpx;color:rgb(0,0,0);font-size:32.8125rpx;", "content": { "lists": ["一天一次", "两天一次", "一个星期最多三次", "一个星期至少一次", "一个月不到三次"], "title": "秋天的你，多久洗一次澡？", "formCompid": "form_vessel2" }, "customFeature": { "lineBackgroundColor": "rgb(147, 196, 125)", "lineBackgroundImage": "", "secColor": "#ffffff", "secFontSize": "16px", "secLineHeight": "35px", "selectAmount": 1, "secFontWeight": "bold", "secFontStyle": "", "secTextDecoration": "" }, "animations": [], "compId": "data.content[0]", "formCompid": "form_vessel2", "segment_required": 0, "parentCompid": "form_vessel2", "titleStyle": "color:#ffffff;font-size:37.5rpx;font-weight:bold;background-color:rgb(147, 196, 125);line-height:82.03125rpx;margin-left:auto;" }], "customFeature": { "form": "" }, "animations": [], "page_form": "", "compId": "form_vessel2", "form": "", "field_info": [], "formCompid": "form_vessel2" }, 
   
   "form_vessel3": { "type": "form-vessel", "style": "background-color:rgba(0, 0, 0, 0);opacity:1;margin-left:auto;", "content": [{ "type": "select-ele", "style": "background-color:rgba(0, 0, 0, 0);margin-top:0;line-height:65.625rpx;opacity:1;margin-right:auto;width:750rpx;color:rgb(0,0,0);font-size:32.8125rpx;margin-left:auto;", "content": { "lists": ["会，承包了多半家务", "会，心血来潮时", "会，被家长要求时", "会，仅打扫自己的房间", "会，在迫不得已时", "几乎不会"], "title": "在家时，你会做家务吗？", "formCompid": "form_vessel3" }, "customFeature": { "lineBackgroundColor": "rgb(147, 196, 125)", "lineBackgroundImage": "", "secColor": "#ffffff", "secFontSize": "16px", "secLineHeight": "35px", "selectAmount": 1, "secFontWeight": "bold", "secFontStyle": "", "secTextDecoration": "" }, "animations": [], "compId": "data.content[0]", "formCompid": "form_vessel3", "segment_required": 0, "parentCompid": "form_vessel3", "titleStyle": "color:#ffffff;font-size:37.5rpx;font-weight:bold;background-color:rgb(147, 196, 125);line-height:82.03125rpx;margin-left:auto;" }], "customFeature": { "form": "" }, "animations": [], "page_form": "", "compId": "form_vessel3", "form": "", "field_info": [], "formCompid": "form_vessel3" },

   "form_vessel4": { "type": "form-vessel", "style": "background-color:rgba(0, 0, 0, 0);opacity:1;margin-left:auto;", "content": [{ "type": "select-ele", "style": "background-color:rgba(0, 0, 0, 0);margin-top:0;line-height:65.625rpx;opacity:1;margin-right:auto;width:750rpx;color:rgb(0,0,0);font-size:32.8125rpx;margin-left:auto;", "content": { "lists": ["不喜欢吃重口味的配料", "有时会放辣椒，但拒绝大蒜", "会放适量的各种调料", "十分爱吃辣椒", "十分爱吃大蒜", "无所谓，都可以接受"], "title": "吃饭的时候，你会放什么配料？", "formCompid": "form_vessel4" }, "customFeature": { "lineBackgroundColor": "rgb(147, 196, 125)", "lineBackgroundImage": "", "secColor": "#ffffff", "secFontSize": "16px", "secLineHeight": "35px", "selectAmount": 1, "secFontWeight": "bold", "secFontStyle": "", "secTextDecoration": "" }, "animations": [], "compId": "data.content[0]", "formCompid": "form_vessel4", "segment_required": 0, "parentCompid": "form_vessel4", "titleStyle": "color:#ffffff;font-size:37.5rpx;font-weight:bold;background-color:rgb(147, 196, 125);line-height:82.03125rpx;margin-left:auto;" }], "customFeature": { "form": "" }, "animations": [], "page_form": "", "compId": "form_vessel4", "form": "", "field_info": [], "formCompid": "form_vessel4" },

   "form_vessel5": { "type": "form-vessel", "style": "background-color:rgba(0, 0, 0, 0);opacity:1;margin-left:auto;", "content": [{ "type": "select-ele", "style": "background-color:rgba(0, 0, 0, 0);margin-top:0;line-height:65.625rpx;opacity:1;margin-right:auto;width:750rpx;color:rgb(0,0,0);font-size:32.8125rpx;margin-left:auto;", "content": { "lists": ["每天都换", "两天一换", "脏了或者产生异味了才换", "至少一周一次", "几乎不换"], "title": "夏天的时候，你换洗衣服的频率如何呢？", "formCompid": "form_vessel5" }, "customFeature": { "lineBackgroundColor": "rgb(147, 196, 125)", "lineBackgroundImage": "", "secColor": "#ffffff", "secFontSize": "16px", "secLineHeight": "35px", "selectAmount": 1, "secFontWeight": "bold", "secFontStyle": "", "secTextDecoration": "" }, "animations": [], "compId": "data.content[0]", "formCompid": "form_vessel5", "segment_required": 0, "parentCompid": "form_vessel5", "titleStyle": "color:#ffffff;font-size:37.5rpx;font-weight:bold;background-color:rgb(147, 196, 125);line-height:82.03125rpx;margin-left:auto;" }], "customFeature": { "form": "" }, "animations": [], "page_form": "", "compId": "form_vessel5", "form": "", "field_info": [], "formCompid": "form_vessel5" },

   "form_vessel6": { "type": "form-vessel", "style": "background-color:rgba(0, 0, 0, 0);opacity:1;margin-left:auto;", "content": [{ "type": "select-ele", "style": "background-color:rgba(0, 0, 0, 0);margin-top:0;line-height:65.625rpx;opacity:1;margin-right:auto;width:750rpx;color:rgb(0,0,0);font-size:32.8125rpx;margin-left:auto;", "content": { "lists": ["22点之前", "22点-23点", "23点-24点", "24点-凌晨1点", "凌晨1点-凌晨2点","凌晨2点之后"], "title": "工作日，你可以接受多晚休息？", "formCompid": "form_vessel6" }, "customFeature": { "lineBackgroundColor": "rgb(147, 196, 125)", "lineBackgroundImage": "", "secColor": "#ffffff", "secFontSize": "16px", "secLineHeight": "35px", "selectAmount": 1, "secFontWeight": "bold", "secFontStyle": "", "secTextDecoration": "" }, "animations": [], "compId": "data.content[0]", "formCompid": "form_vessel6", "segment_required": 0, "parentCompid": "form_vessel6", "titleStyle": "color:#ffffff;font-size:37.5rpx;font-weight:bold;background-color:rgb(147, 196, 125);line-height:82.03125rpx;margin-left:auto;" }], "customFeature": { "form": "" }, "animations": [], "page_form": "", "compId": "form_vessel6", "form": "", "field_info": [], "formCompid": "form_vessel6" },

   "form_vessel7": { "type": "form-vessel", "style": "background-color:rgba(0, 0, 0, 0);opacity:1;margin-left:auto;", "content": [{ "type": "select-ele", "style": "background-color:rgba(0, 0, 0, 0);margin-top:0;line-height:65.625rpx;opacity:1;margin-right:auto;width:750rpx;color:rgb(0,0,0);font-size:32.8125rpx;margin-left:auto;", "content": { "lists": ["7点以前", "8点左右", "9点-10点", "中午", "下午", "自然醒，能睡到几点是几点"], "title": "周末一般几点起床呢？", "formCompid": "form_vessel7" }, "customFeature": { "lineBackgroundColor": "rgb(147, 196, 125)", "lineBackgroundImage": "", "secColor": "#ffffff", "secFontSize": "16px", "secLineHeight": "35px", "selectAmount": 1, "secFontWeight": "bold", "secFontStyle": "", "secTextDecoration": "" }, "animations": [], "compId": "data.content[0]", "formCompid": "form_vessel7", "segment_required": 0, "parentCompid": "form_vessel7", "titleStyle": "color:#ffffff;font-size:37.5rpx;font-weight:bold;background-color:rgb(147, 196, 125);line-height:82.03125rpx;margin-left:auto;" }], "customFeature": { "form": "" }, "animations": [], "page_form": "", "compId": "form_vessel7", "form": "", "field_info": [], "formCompid": "form_vessel7" },

   "form_vessel8": { "type": "form-vessel", "style": "background-color:rgba(0, 0, 0, 0);opacity:1;margin-left:auto;", "content": [{ "type": "select-ele", "style": "background-color:rgba(0, 0, 0, 0);margin-top:0;line-height:65.625rpx;opacity:1;margin-right:auto;width:750rpx;color:rgb(0,0,0);font-size:32.8125rpx;margin-left:auto;", "content": { "lists": ["几乎没有人能改变我的学习方式", "身边的学习氛围可能会对我产生一点影响", "在身边的人都很努力／懒惰的前提下，我会受到他们的影响", "十分容易受到他人的影响"], "title": "你的学习习惯容易被他人影响吗？", "formCompid": "form_vessel8" }, "customFeature": { "lineBackgroundColor": "rgb(147, 196, 125)", "lineBackgroundImage": "", "secColor": "#ffffff", "secFontSize": "16px", "secLineHeight": "35px", "selectAmount": 1, "secFontWeight": "bold", "secFontStyle": "", "secTextDecoration": "" }, "animations": [], "compId": "data.content[0]", "formCompid": "form_vessel8", "segment_required": 0, "parentCompid": "form_vessel8", "titleStyle": "color:#ffffff;font-size:37.5rpx;font-weight:bold;background-color:rgb(147, 196, 125);line-height:82.03125rpx;margin-left:auto;" }], "customFeature": { "form": "" }, "animations": [], "page_form": "", "compId": "form_vessel8", "form": "", "field_info": [], "formCompid": "form_vessel8" },

   "form_vessel9": { "type": "form-vessel", "style": "background-color:rgba(0, 0, 0, 0);opacity:1;margin-left:auto;", "content": [{ "type": "select-ele", "style": "background-color:rgba(0, 0, 0, 0);margin-top:0;line-height:65.625rpx;opacity:1;margin-right:auto;width:750rpx;color:rgb(0,0,0);font-size:32.8125rpx;margin-left:auto;", "content": { "lists": ["十分期待集体生活，喜欢三五成群地行动", "朋友不用太多，只要有一个如影随形的朋友就够了", "更倾向于有一个独立的个人空间，但也需要朋友", "不喜欢不必要的打扰，习惯独来独往","无所谓"], "title": "你对集体生活有怎样的看法？", "formCompid": "form_vessel9" }, "customFeature": { "lineBackgroundColor": "rgb(147, 196, 125)", "lineBackgroundImage": "", "secColor": "#ffffff", "secFontSize": "16px", "secLineHeight": "35px", "selectAmount": 1, "secFontWeight": "bold", "secFontStyle": "", "secTextDecoration": "" }, "animations": [], "compId": "data.content[0]", "formCompid": "form_vessel9", "segment_required": 0, "parentCompid": "form_vessel9", "titleStyle": "color:#ffffff;font-size:37.5rpx;font-weight:bold;background-color:rgb(147, 196, 125);line-height:82.03125rpx;margin-left:auto;" }], "customFeature": { "form": "" }, "animations": [], "page_form": "", "compId": "form_vessel9", "form": "", "field_info": [], "formCompid": "form_vessel9" },

   "form_vessel10": {"type": "form-vessel", "style": "background-color:rgba(0, 0, 0, 0);opacity:1;margin-left:auto;", "content": [{"type": "select-ele", "style": "background-color:rgba(0, 0, 0, 0);margin-top:0;line-height:65.625rpx;opacity:1;margin-right:auto;width:750rpx;color:rgb(0,0,0);font-size:32.8125rpx;margin-left:auto;", "content": { "lists": ["喜欢一个多元的环境，交不同的朋友", "喜欢和我有很多相似点的人相处", "无所谓,随遇而安"], "title": "喜欢和性格，观点，背景不同相处还是和有很多相似点的人相处？", "formCompid": "form_vessel10" }, "customFeature": { "lineBackgroundColor": "rgb(147, 196, 125)", "lineBackgroundImage": "", "secColor": "#ffffff", "secFontSize": "16px", "secLineHeight": "35px", "selectAmount": 1, "secFontWeight": "bold", "secFontStyle": "", "secTextDecoration": "" }, "animations": [], "compId": "data.content[0]", "formCompid": "form_vessel10", "segment_required": 0, "parentCompid": "form_vessel10", "titleStyle": "color:#ffffff;font-size:37.5rpx;font-weight:bold;background-color:rgb(147, 196, 125);line-height:82.03125rpx;margin-left:auto;" }], "customFeature": { "form": "" }, "animations": [], "page_form": "", "compId": "form_vessel10", "form": "", "field_info": [], "formCompid": "form_vessel10" },

   "form_vessel11": { "type": "form-vessel", "style": "background-color:rgba(0, 0, 0, 0);opacity:1;margin-left:auto;", "content": [{ "type": "select-ele", "style": "background-color:rgba(0, 0, 0, 0);margin-top:0;line-height:65.625rpx;opacity:1;margin-right:auto;width:750rpx;color:rgb(0,0,0);font-size:32.8125rpx;margin-left:auto;", "content": { "lists": ["做一个学霸", "学习社交两不误", "好好玩，把上辈子没玩过的东西玩一遍", "沉迷于爱情","暂时没想法"], "title": "在大学里想成为怎样的人？", "formCompid": "form_vessel11" }, "customFeature": { "lineBackgroundColor": "rgb(147, 196, 125)", "lineBackgroundImage": "", "secColor": "#ffffff", "secFontSize": "16px", "secLineHeight": "35px", "selectAmount": 1, "secFontWeight": "bold", "secFontStyle": "", "secTextDecoration": "" }, "animations": [], "compId": "data.content[0]", "formCompid": "form_vessel11", "segment_required": 0, "parentCompid": "form_vessel11", "titleStyle": "color:#ffffff;font-size:37.5rpx;font-weight:bold;background-color:rgb(147, 196, 125);line-height:82.03125rpx;margin-left:auto;" }], "customFeature": { "form": "" }, "animations": [], "page_form": "", "compId": "form_vessel11", "form": "", "field_info": [], "formCompid": "form_vessel11" },

   "form_vessel12": { "type": "form-vessel", "style": "background-color:rgba(0, 0, 0, 0);opacity:1;margin-left:auto;", "content": [{ "type": "select-ele", "style": "background-color:rgba(0,0,0,0);margin-top:0;line-height:65.625rpx;opacity:1;margin-left:auto;margin-right:auto;width:750rpx;color:rgb(0,0,0);font-size:32.8125rpx;", "content": { "lists": ["爱干净", "勤劳", "学霸", "性格开朗", "会玩", "生活作息规律"], "title": "你对未来室友的期望是怎样的呢？", "formCompid": "form_vessel12" }, "customFeature": { "lineBackgroundColor": "rgb(147, 196, 125)", "lineBackgroundImage": "", "secColor": "#ffffff", "secFontSize": "16px", "secLineHeight": "35px", "selectAmount": "6", "secFontWeight": "bold", "secFontStyle": "", "secTextDecoration": "" }, "animations": [], "compId": "data.content[0]", "formCompid": "form_vessel12", "segment_required": 0, "parentCompid": "form_vessel12", "titleStyle": "color:#ffffff;font-size:37.5rpx;font-weight:bold;background-color:rgb(147, 196, 125);line-height:82.03125rpx;margin-left:auto;" },], "customFeature": { "form": "", "link": "-1", "source": "none" }, "animations": [], "page_form": "", "compId": "form_vessel12", "form": "", "field_info": [], "formCompid": "form_vessel12" },

   "form_vessel13": { "type": "form-vessel", "style": "background-color:rgba(0, 0, 0, 0);opacity:1;margin-left:auto;", "content": [{ "type": "select-ele", "style": "background-color:rgba(0, 0, 0, 0);margin-top:0;line-height:65.625rpx;opacity:1;margin-right:auto;width:750rpx;color:rgb(0,0,0);font-size:32.8125rpx;margin-left:auto;", "content": { "lists": ["在房间里打游戏", "在床上躺一天看剧，看视频", "和朋友出去玩", "出去锻炼，体育运动", "好好学习，提升自己","终于有时间做自己喜欢做的事情"], "title": "如果没什么事情的话，一般如何过周末？", "formCompid": "form_vessel13" }, "customFeature": { "lineBackgroundColor": "rgb(147, 196, 125)", "lineBackgroundImage": "", "secColor": "#ffffff", "secFontSize": "16px", "secLineHeight": "35px", "selectAmount": 1, "secFontWeight": "bold", "secFontStyle": "", "secTextDecoration": "" }, "animations": [], "compId": "data.content[0]", "formCompid": "form_vessel13", "segment_required": 0, "parentCompid": "form_vessel13", "titleStyle": "color:#ffffff;font-size:37.5rpx;font-weight:bold;background-color:rgb(147, 196, 125);line-height:82.03125rpx;margin-left:auto;" }], "customFeature": { "form": "" }, "animations": [], "page_form": "", "compId": "form_vessel13", "form": "", "field_info": [], "formCompid": "form_vessel13" },

   "form_vessel14": { "type": "form-vessel", "style": "background-color:rgba(0, 0, 0, 0);opacity:1;margin-left:auto;", "content": [{ "type": "select-ele", "style": "background-color:rgba(0,0,0,0);margin-top:0;line-height:65.625rpx;opacity:1;margin-left:auto;margin-right:auto;width:750rpx;color:rgb(0,0,0);font-size:32.8125rpx;", "content": { "lists": ["狼人杀", "三国杀", "斗地主", "UNO", "德州扑克", " 阿瓦隆", "谁是大老板", "谁是卧底","麻将","无"], "title": "你玩过哪些桌游呢？", "formCompid": "form_vessel14" }, "customFeature": { "lineBackgroundColor": "rgb(147, 196, 125)", "lineBackgroundImage": "", "secColor": "#ffffff", "secFontSize": "16px", "secLineHeight": "35px", "selectAmount": "9", "secFontWeight": "bold", "secFontStyle": "", "secTextDecoration": "" }, "animations": [], "compId": "data.content[0]", "formCompid": "form_vessel14", "segment_required": 0, "parentCompid": "form_vessel14", "titleStyle": "color:#ffffff;font-size:37.5rpx;font-weight:bold;background-color:rgb(147, 196, 125);line-height:82.03125rpx;margin-left:auto;" },], "customFeature": { "form": "", "link": "-1", "source": "none" }, "animations": [], "page_form": "", "compId": "form_vessel14", "form": "", "field_info": [], "formCompid": "form_vessel14" },

   "form_vessel15": { "type": "form-vessel", "style": "background-color:rgba(0, 0, 0, 0);opacity:1;margin-left:auto;", "content": [{ "type": "select-ele", "style": "background-color:rgba(0, 0, 0, 0);margin-top:0;line-height:65.625rpx;opacity:1;margin-right:auto;width:750rpx;color:rgb(0,0,0);font-size:32.8125rpx;margin-left:auto;", "content": { "lists": ["打一架", "不理ta", "正常生活，该怎样就怎样，还是会和ta说话", "寻找机会沟通解决问题"], "title": "当你和你的室友发生矛盾时，你会怎么处理？", "formCompid": "form_vessel15" }, "customFeature": { "lineBackgroundColor": "rgb(147, 196, 125)", "lineBackgroundImage": "", "secColor": "#ffffff", "secFontSize": "16px", "secLineHeight": "35px", "selectAmount": 1, "secFontWeight": "bold", "secFontStyle": "", "secTextDecoration": "" }, "animations": [], "compId": "data.content[0]", "formCompid": "form_vessel15", "segment_required": 0, "parentCompid": "form_vessel15", "titleStyle": "color:#ffffff;font-size:37.5rpx;font-weight:bold;background-color:rgb(147, 196, 125);line-height:82.03125rpx;margin-left:auto;" }], "customFeature": { "form": "" }, "animations": [], "page_form": "", "compId": "form_vessel15", "form": "", "field_info": [], "formCompid": "form_vessel15" },

   "form_vessel16": { "type": "form-vessel", "style": "background-color:rgba(0, 0, 0, 0);opacity:1;margin-left:auto;", "content": [{ "type": "select-ele", "style": "background-color:rgba(0,0,0,0);margin-top:0;line-height:65.625rpx;opacity:1;margin-left:auto;margin-right:auto;width:750rpx;color:rgb(0,0,0);font-size:32.8125rpx;", "content": { "lists": ["生活习惯差", "不诚实", "自私", "没有追求，颓废，懒惰", "易怒，爱计较", "爱攀比"], "title": "你能容忍别人的哪些缺点呢？", "formCompid": "form_vessel16" }, "customFeature": { "lineBackgroundColor": "rgb(147, 196, 125)", "lineBackgroundImage": "", "secColor": "#ffffff", "secFontSize": "16px", "secLineHeight": "35px", "selectAmount": "6", "secFontWeight": "bold", "secFontStyle": "", "secTextDecoration": "" }, "animations": [], "compId": "data.content[0]", "formCompid": "form_vessel16", "segment_required": 0, "parentCompid": "form_vessel16", "titleStyle": "color:#ffffff;font-size:37.5rpx;font-weight:bold;background-color:rgb(147, 196, 125);line-height:82.03125rpx;margin-left:auto;" },], "customFeature": { "form": "", "link": "-1", "source": "none" }, "animations": [], "page_form": "", "compId": "form_vessel16", "form": "", "field_info": [], "formCompid": "form_vessel16" },

   "form_vessel17": { "type": "form-vessel", "style": "background-color:rgba(0, 0, 0, 0);opacity:1;margin-left:auto;", "content": [{ "type": "select-ele", "style": "background-color:rgba(0, 0, 0, 0);margin-top:0;line-height:65.625rpx;opacity:1;margin-right:auto;width:750rpx;color:rgb(0,0,0);font-size:32.8125rpx;margin-left:auto;", "content": { "lists": ["偶尔会喝，但是一个人不会去喝", "不会，太贵了，不划算", "无所谓，味道好的就会喝", "有时会喝，放松一下自己","常喝"], "title": "你平时会喝星巴克这种一杯30多块的饮料吗？", "formCompid": "form_vessel17" }, "customFeature": { "lineBackgroundColor": "rgb(147, 196, 125)", "lineBackgroundImage": "", "secColor": "#ffffff", "secFontSize": "16px", "secLineHeight": "35px", "selectAmount": 1, "secFontWeight": "bold", "secFontStyle": "", "secTextDecoration": "" }, "animations": [], "compId": "data.content[0]", "formCompid": "form_vessel17", "segment_required": 0, "parentCompid": "form_vessel17", "titleStyle": "color:#ffffff;font-size:37.5rpx;font-weight:bold;background-color:rgb(147, 196, 125);line-height:82.03125rpx;margin-left:auto;" }], "customFeature": { "form": "" }, "animations": [], "page_form": "", "compId": "form_vessel17", "form": "", "field_info": [], "formCompid": "form_vessel17" },


   "form_vessel18": { "type": "form-vessel", "style": "background-color:rgba(0, 0, 0, 0);opacity:1;margin-left:auto;", "content": [{ "type": "select-ele", "style": "background-color:rgba(0, 0, 0, 0);margin-top:0;line-height:65.625rpx;opacity:1;margin-right:auto;width:750rpx;color:rgb(0,0,0);font-size:32.8125rpx;margin-left:auto;", "content": { "lists": ["可爱多", "不会，太贵了，不划算", "梦龙", "哈根达斯", "Cold Stone冰激凌", "DQ", "东北大板", "Godiva冰激凌", "爱茜茜里", "八喜", "蒙牛", "光明","伊利","便利店的"], "title": "下列品牌的冰激凌你吃过哪些？", "formCompid": "form_vessel18" }, "customFeature": { "lineBackgroundColor": "rgb(147, 196, 125)", "lineBackgroundImage": "", "secColor": "#ffffff", "secFontSize": "16px", "secLineHeight": "35px", "selectAmount": 13, "secFontWeight": "bold", "secFontStyle": "", "secTextDecoration": "" }, "animations": [], "compId": "data.content[0]", "formCompid": "form_vessel18", "segment_required": 0, "parentCompid": "form_vessel18", "titleStyle": "color:#ffffff;font-size:37.5rpx;font-weight:bold;background-color:rgb(147, 196, 125);line-height:82.03125rpx;margin-left:auto;" }], "customFeature": { "form": "" }, "animations": [], "page_form": "", "compId": "form_vessel18", "form": "", "field_info": [], "formCompid": "form_vessel18" },

   warnSize: 'default',
 
    },
  need_login: true,
  page_router: 'match',
  page_form: 'none',
  list_compids_params: [],
  user_center_compids_params: [],
  goods_compids_params: [],
  prevPage: 0,
  tostoreComps: [],
  carouselGroupidsParams: [],
  relobj_auto: [],
  bbsCompIds: [],
  dynamicVesselComps: [],
  communityComps: [],
  franchiseeComps: [],
  cityLocationComps: [],
  seckillOnLoadCompidParam: [],
  dynamicClassifyGroupidsParams: [],
  videoListComps: [],
  videoProjectComps: [],
  returnToVersionFlag: true,
  requesting: false,
  requestNum: 1,

  onLoad: function (e) {
    app.onPageLoad(e);
  },
  dataInitial: function () {
    app.pageDataInitial();
  },
  inputChange: function (e) {
    app.inputChange(e);
  },
  bindDateChange: function (e) {
    app.bindDateChange(e);
  },
  bindTimeChange: function (e) {
    app.bindTimeChange(e);
  },
  bindSelectChange: function (e) {
    app.bindSelectChange(e);
  },
  bindScoreChange: function (e) {
    app.bindScoreChange(e);
  },
  submitForm: function (e) {
    app.submitForm(e);
  },


  //设计按钮的大小
  setSize: function () {
    this.setData({
      warnSize: this.data.defaultSize == 'default' ? 'mini' : 'default',
    })
  },
  setWarn: function () {
    console.log('setWarn....')
  },


};
Page(pageData);
